mindmap
  root)Gestion Changement(
        Finalité
            Gérer changement
                limiter impact
        objectif
            maitrier modification Configuration
            evaluer risque changement
            adapter procédure changement
            évolution efficacement 1er coup
        Indicateur
            nb changements
                période
                approuvé
                caché
            nombre incidents
                Par changement
            Taux réussite
            Taux retours arriére
        Changement
            CI
                Ajout
                modification
                Suppresion
            RFC
        Activité
            RFC
                Enregistrer
                Classifier
                Approuver
            Changement
                Préparer
                Tester
                Autoriser
            Revue PIR
            Cloture CHG
        Niveau
            Priorité
                impact
                délai
            categorie
                impact
                ressources
        Manager
        CAB
        Difficultés
            Bureaucratie
                Trop stricte
            Resistance culturelle
            Non respect procédure
            Ressources insuffisants
            manque information
                classification
                approbation
        Recommandations
            En parallèle
                Mise en production
            changement caché
                sensibiliser impact négatif
            changement non autorisé
                Detecter
        Bénéfice
            Réduire impact négatif changement
            maitrise coup avant CHG
            compétence fonction métier
            diminution intérruptions
            amélioration image DSI